{% set name = "lona" %}
{% set version = "1.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lona-{{ version }}.tar.gz
  sha256: 61f88f08bc13f6296dbbd0d987039854ed72b3a12f0b11f210a7b5a8332add6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.0
  run:
    - aiohttp >=3,<4
    - jinja2
    - python >=3.8
    - rlpython
    - typing_extensions

test:
  imports:
    - lona
  commands:
    - pip check
    - lona --help
  requires:
    - pip

about:
  home: https://github.com/lona-web-org/lona
  doc_url: https://lona-web.org/
  summary: Write responsive web apps in full python
  license: MIT
  license_file: LICENSE.txt
  description: |
    Lona is a web application framework, designed to write responsive web apps
     in full Python. Web is a solved problem in Python since ages, but
     traditionally Python handles only the server side. If you want to have
     client side interaction like click events or you want update content live,
     you have to write an additional Javascript application. Lona handles the
     server side and the client side, and provides a simple, pythonic API to
     write self contained views. Lona comes with a Javascript based browser
     library that speaks a specialized protocol with the backend. This protocol
     specifies messages like "hey frontend, please show $HTML" and "hey
     backend, someone clicked on node XY"

extra:
  recipe-maintainers:
    - thewchan
