{% set name = "lona" %}
{% set version = "1.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lona-{{ version }}.tar.gz
  sha256: 2dc91de5212cf7527d9436ddf9404153090e811e3db7101d3e6f7ef4b74bc984

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.0
  run:
    - python >=3.8
    - aiohttp >=3,<4
    - watchfiles
    - jinja2
    - rlpython
    - typing_extensions

test:
  imports:
    - lona
  commands:
    - pip check
    - lona --help
  requires:
    - pip

about:
  home: https://github.com/lona-web-org/lona
  doc_url: https://lona-web.org/
  summary: Write responsive web apps in full python
  license: MIT
  license_file: LICENSE.txt
  description: |
    Lona is a web application framework, designed to write responsive web apps
     in full Python. Web is a solved problem in Python since ages, but
     traditionally Python handles only the server side. If you want to have
     client side interaction like click events or you want update content live,
     you have to write an additional Javascript application. Lona handles the
     server side and the client side, and provides a simple, pythonic API to
     write self contained views. Lona comes with a Javascript based browser
     library that speaks a specialized protocol with the backend. This protocol
     specifies messages like "hey frontend, please show $HTML" and "hey
     backend, someone clicked on node XY"

extra:
  recipe-maintainers:
    - thewchan
